[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.35"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"
